# docker-compose.build.yml
# This file is used for building images on a remote CI/CD server or the AWS EC2 instance.
# It does NOT use the Chinese mirror.

services:
  web:
    image: crpi-34v4qt829vtet2cy.cn-hangzhou.personal.cr.aliyuncs.com/vss_edge/workbench:v1.2.0-alpha.4.fix # Define the tag for the built image
    restart: always

  worker:
    image: crpi-34v4qt829vtet2cy.cn-hangzhou.personal.cr.aliyuncs.com/vss_edge/workbench:v1.2.0-alpha.4.fix # Use the same tag
    restart: always

  subeditor:
    image: crpi-34v4qt829vtet2cy.cn-hangzhou.personal.cr.aliyuncs.com/vss_edge/subeditor:v1.2.0-alpha.4 # 目前subeditor并没有进行镜像版本管理
    restart: always